Feature/actuallytaylor/version upgrade
RIT-EVT/canopen-stack pull request #2
Opened 2023-10-14 14:35 UTC by ActuallyTaylor

Upgrades the CANOpen version

2023-10-29 01:01 UTC, mjmagee991 requested changes
Minor details

2023-10-29 01:01 UTC, mjmagee991 commented on src/CMakeLists.txt
> +)
Add a newline

2023-10-29 01:01 UTC, mjmagee991 commented on src/CMakeLists.txt
> +        PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/service/cia305>
Move `PUBLIC` onto the line above to match all the other includes

2023-11-03 23:47 UTC, mjmagee991 approved these changes
Nice work

2023-11-28 00:18 UTC, ishan-renjen approved these changes

2023-11-30 23:48 UTC, merged